### ISSUE TITLE
`setup` command is missing `--undo-buffer-size` flag

### ISSUE THREAD

**Issue by anthonyra** [streamingfast/substreams-sink-sql#49]
If you run the following command
```ini
substreams-sink-sql setup $DSN docs/tutorial/substreams-clickhouse.yaml
new psql loader: driver clickhouse does not support reorg handling. You must use set a non-zero undo-buffer-size
```

It'll fail since you need to set `undo-buffer-size` > 0. In change log it recommends 12. But
```ini
substreams-sink-sql setup $DSN docs/tutorial/substreams-clickhouse.yaml --undo-buffer-size=12
unknown flag: --undo-buffer-size
```

**Comment by sduchesneau** [comment]
nice catch @anthonyra !
Instead of adding the support for that flag, I made the setup aware of the backend capabilities: it will now automatically create the reorg table on postgres, and not try to do so on clickhouse.
The user can still decide if it wants to use the reorg or the undo-buffer when running on postgres, the behavior will be unchanged for clickhouse.
